name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test application
        run: |
          echo "Running tests..."
          test -f index.html
          echo "Test passed"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html
            sudo rm -rf *
            sudo git clone https://github.com/AhmedAyan18/aws-cicd-demo.git temp
            sudo cp -r temp/* .
            sudo rm -rf temp
            sudo systemctl restart apache2

      - name: Deployment successful
        run: echo "Application deployed successfully!"
